sudo: false
language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '7'

before_install:
  - npm i -g npm@latest

before_script:
  - npm run lint

script:
  - npm test

branches:
  only:
    - "master"